
version: 2
jobs:
  build:
    docker:
      - image: stackfeed/circle-shell
    environment:
      PROJECT: spark
      NAMESPACE: actionml
      PUSH_NAMESPACES: actionml
      CONTINUOUS_INTEGRATION: "yes"

    steps:
      -
        run:
          name: Install ci-scripts
          command: |
            echo 'export PATH=$PATH:~/ci-scripts' >> $BASH_ENV
            wget -qO - https://github.com/stackfeed/ci-scripts/raw/master/install.sh | sh -s -- -r v0.2
      -
        run:
          name: Setup dependencies
          command: |
            latests=$(wget -qO - https://raw.githubusercontent.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/master/.latests)
            version=${CIRCLE_TAG#v}
            [ -n "$version" ] || version=$(echo "${latests}" | cut -f1 -d' ')
            printf 'export LATESTS=%s\n' ${latests} >> $BASH_ENV
            printf 'export VERSION=%s\n' ${version} >> $BASH_ENV
      -
        setup_remote_docker
      -
        checkout
      -
        run:
          name: Build docker image
          command: |
            SHORT_GIT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
            DATE_BUILD=$(date +'%Y-%m-%d')

            case "${CIRCLE_BRANCH}" in
              master|develop|devops)
              docker image build -f Dockerfile \
                --build-arg release=${CIRCLE_TAG:-build} \
                --build-arg version=${VERSION%%-*} \
                --build-arg GIT_HASH=$SHORT_GIT_HASH --build-arg DATE_BUILD=$DATE_BUILD \
                --build-arg BRANCH=${CIRCLE_BRANCH} \
                -t actionml/spark:latest ./
              ;;
              *)
              ;;
            esac
      -
        run:
          name: Publish docker image
          command: |
            SHORT_GIT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
            DATE_BUILD=$(date +'%Y-%m-%d')
            
            case "${CIRCLE_BRANCH}" in
              "master")
                docker image push actionml/spark:latest
                curl -XPOST "https://hooks.microbadger.com/images/${NAMESPACE}/${PROJECT}/${MICROBADGER_TOKEN}"
              ;;
              "develop")
                
                docker tag actionml/spark:latest actionml/spark:${CIRCLE_BRANCH}
                docker image push actionml/spark:${CIRCLE_BRANCH}
                
                docker tag actionml/spark:latest actionml/spark:${CIRCLE_BRANCH}-$SHORT_GIT_HASH
                docker image push actionml/spark:${CIRCLE_BRANCH}-$SHORT_GIT_HASH
                
                docker tag actionml/spark:latest actionml/spark:${CIRCLE_BRANCH}-$DATE_BUILD
                docker image push actionml/spark:${CIRCLE_BRANCH}-$DATE_BUILD
              ;;
              "devops")
                docker tag actionml/spark:latest actionml/spark:${CIRCLE_BRANCH}
                docker image push actionml/spark:${CIRCLE_BRANCH}
                
                docker tag actionml/spark:latest actionml/spark:${CIRCLE_BRANCH}-$SHORT_GIT_HASH
                docker image push actionml/spark:${CIRCLE_BRANCH}-$SHORT_GIT_HASH
                
                docker tag actionml/spark:latest actionml/spark:${CIRCLE_BRANCH}-$DATE_BUILD
                docker image push actionml/spark:${CIRCLE_BRANCH}-$DATE_BUILD
              ;;
              *)
              ;;
            esac

workflows:
  version: 2
  default:
    jobs:
      - build:
          filters:
            tags:
              only: /^v([0-9]+\.?)+.*/
